#define SAMPLE_RATE 16000
#define MINIMUM_FREQUENCY 0
#define MAXIMUM_FREQUENCY SAMPLE_RATE / 2
#define TIME_COVERED_BY_WINDOW 10
#define TIME_STEP 0.1
#define WINDOW_SIZE TIME_COVERED_BY_WINDOW * SAMPLE_RATE
#define STEP_SIZE TIME_STEP * SAMPLE_RATE
#define RESERVE_SIZE WINDOW_SIZE - STEP_SIZE
#define WINDOW_HEIGHT 512
#define WINDOW_WIDTH TIME_COVERED_BY_WINDOW * 100